version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"  
      - "7687:7687" 
    environment:
      NEO4J_AUTH: neo4j/Dbakroo@2024
    volumes:
      - neo4j-storage:/data  

volumes:
  neo4j-storage:
    driver: local
